# Generated by Django 2.1.7 on 2019-02-22 06:26

from django.db import migrations, models
import django.db.models.deletion
import sku_manage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('number', models.IntegerField(default=sku_manage.models.gen_fla_num, unique=True, verbose_name='Formula#')),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Ingredient Name')),
                ('number', models.PositiveIntegerField(default=sku_manage.models.gen_ingr_num, unique=True, verbose_name='Ingredient#')),
                ('vendor_info', models.TextField(blank=True, verbose_name='Vendor Information')),
                ('package_size', models.FloatField(validators=[sku_manage.models.validate_gt_zero])),
                ('package_size_units', models.CharField(choices=[('Ounce', 'oz.'), ('Pound', 'lb.'), ('Ton', 'ton.'), ('Gram', 'g.'), ('Kilogram', 'kg.'), ('Fluid Ounce', 'fl.oz.'), ('Pint', 'pt.'), ('Quart', 'qt.'), ('Gallon', 'gal.'), ('Milliliter', 'mL'), ('Liter', 'L'), ('Count', 'count')], max_length=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[sku_manage.models.validate_gt_zero])),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(validators=[sku_manage.models.validate_gt_zero])),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku_manage.Formula')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sku_manage.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('shortname', models.CharField(max_length=5, unique=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sku_num', models.IntegerField(default=sku_manage.models.gen_sku_num, unique=True, verbose_name='SKU#')),
                ('case_upc', models.CharField(max_length=12, unique=True, validators=[sku_manage.models.validate_upc], verbose_name='Case UPC')),
                ('unit_upc', models.CharField(max_length=12, validators=[sku_manage.models.validate_upc], verbose_name='Unit UPC')),
                ('unit_size', models.CharField(max_length=256)),
                ('units_per_case', models.PositiveIntegerField(validators=[sku_manage.models.validate_gt_zero])),
                ('formula_scale', models.FloatField(default=1.0, validators=[sku_manage.models.validate_gt_zero], verbose_name='Formula Scale Factor')),
                ('mfg_rate', models.FloatField(validators=[sku_manage.models.validate_gt_zero], verbose_name='Manufacturing Rate')),
                ('comment', models.TextField(blank=True)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sku_manage.Formula')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sku_manage.ProductLine')),
            ],
        ),
        migrations.CreateModel(
            name='SkuMfgLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sku_manage.ManufacturingLine')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku_manage.SKU')),
            ],
        ),
    ]
