# Generated by Django 2.1.5 on 2019-01-21 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sku_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sku_manage.Ingredient')),
            ],
        ),
        migrations.RemoveField(
            model_name='sku',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='ingredientqty',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku_manage.SKU'),
        ),
    ]
