# Generated by Django 2.1.5 on 2019-02-06 03:55

from django.db import migrations, models
import sku_manage.models


class Migration(migrations.Migration):

    dependencies = [
        ('sku_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[sku_manage.models.validate_gt_zero]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='number',
            field=models.IntegerField(blank=True, unique=True, validators=[sku_manage.models.validate_positive], verbose_name='Ingredient#'),
        ),
        migrations.AlterField(
            model_name='ingredientqty',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[sku_manage.models.validate_gt_zero]),
        ),
        migrations.AlterField(
            model_name='sku',
            name='case_upc',
            field=models.DecimalField(decimal_places=0, max_digits=12, unique=True, validators=[sku_manage.models.validate_upc], verbose_name='Case UPC'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unit_upc',
            field=models.DecimalField(decimal_places=0, max_digits=12, validators=[sku_manage.models.validate_upc], verbose_name='Unit UPC'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='units_per_case',
            field=models.IntegerField(validators=[sku_manage.models.validate_gt_zero]),
        ),
    ]
