# Generated by Django 2.1.5 on 2019-02-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sku_manage', '0002_auto_20190206_0013'),
        ('sku_manage', '0002_auto_20190205_2255'),
    ]

    operations = [
    ]
