# Generated by Django 2.1.7 on 2019-02-22 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sku_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturingQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseqty', models.DecimalField(decimal_places=10, max_digits=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing_goals.ManufacturingGoal')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sku_manage.SKU')),
            ],
        ),
    ]
