# Generated by Django 2.1.5 on 2019-02-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturinggoal',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
