# Generated by Django 2.1.5 on 2019-02-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing_goals', '0002_auto_20190205_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturinggoal',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
